import { Component } from '@angular/core';

@Component({
  selector: 'app-about-us',
  templateUrl: './about-us.component.html',
  styleUrls: ['./about-us.component.scss']
})
export class AboutUsComponent {
  description: string = "Ninja IT has started its journey to ensure a sustainable future for businesses and the community. We are a research and software development organisation with sites across the United Kingdom and Bangladesh. We've begun research in behavioural computer science, technology, health informatics, education, and community. Our priority is to help businesses prepare and sustain for the fifth industrial revolution.The future of the current digital age is to prioritise data - driven technology.Therefore, we assess each company with our research for them to be ready and gradually transform them toward data - driven decision - making.We know it is not easy for some businesses and their employees to accept changes so we create pathways by staying close to the original system.Then we work closely with them to help them understand the significance and prepare them for the change. We are also helping disadvantaged individuals in the United Kingdom and Bangladesh through research, training, and development activities.Currently, we are working on several research projects with the Peoples' Republic of Bangladesh to understand the intangible heritage. Our research projects are World Health Aid, (WHA), a telemedicine project, Tikar Boi, (a vaccination diary), E-Commerce solutions, DcoTrack (Data collection tools), EventsTri (Events listing and managing) and many more. Our Work - Based Learning(WBL) programme is one of the flagship programmes that is specially designed for freshers, young enthusiasts and the workforce.Our developed model not only trains pupils with our experienced colleagues, but it also provides supervised learning for the workforce to gain educational qualifications.Furthermore, our next - generation telemedicine and health advice platform(WHA) is funded by the Future & Emerging Technologies Theme at the University of Portsmouth, the Global Challenges Research Fund(GCRF) and the ICT ministry of Bangladesh iDEA Project Innovation Fund.It helps people in the UK and Bangladesh triage and understand the severity of a disease or condition. Our focus on upcoming projects is to take care of the environment and of those deprived in society, discriminated against for their sexual orientation, beliefs or disabilities.Our research will point out the gaps, and we draw a strategic plan to resolve them.We know it's a collective responsibility and we can't do it alone, so we'll create a support bubble with our partners and collaborators to strike together. At the heart of our solutions, we will combine modern technologies, Expert Systems and Artificial Intelligence(AI), Machine Learning(ML), Data Science, Computer Vision, Natural Language Processing(NLP), and the Internet of Things(IoT) to understand and resolve problems."

}
