export const BANNER: any[] = [
  {
    _id: '1',
    name: 'new title',
    title: 'Lorem ipsum',
    subTitle: 'Ideology 1',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At exercitationem voluptate, voluptatum voluptates quia dolore. Reiciendis iure eum hic tempore? Consequatur, vel voluptate! Dolor quas culpa molestiae! Quo, quam voluptatem.',
    webBg: '',
    mobileBg: null,
    webImage: './assets/images/carousel/Image1.png',
    mobileImage: null,
    bannerType: null,
    url: null,
    isExternalUrl: null,
    isStatic: false
  },
  {
    _id: '2',
    name: 'new title',
    title: 'Lorem ipsum',
    subTitle: 'Ideology 2',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At exercitationem voluptate, voluptatum voluptates quia dolore. Reiciendis iure eum hic tempore? Consequatur, vel voluptate! Dolor quas culpa molestiae! Quo, quam voluptatem.',
    webBg: './assets/images/carousel/background/bg2.jpg',
    mobileBg: null,
    webImage: './assets/images/carousel/Image2.png',
    mobileImage: null,
    bannerType: null,
    url: null,
    isExternalUrl: null,
    isStatic: false
  },
  {
    _id: '3',
    name: 'new title',
    title: 'Lorem ipsum',
    subTitle: 'Ideology 3',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. At exercitationem voluptate, voluptatum voluptates quia dolore. Reiciendis iure eum hic tempore? Consequatur, vel voluptate! Dolor quas culpa molestiae! Quo, quam voluptatem.',
    webBg: './assets/images/carousel/background/bg3.jpg',
    mobileBg: null,
    webImage: './assets/images/carousel/Image3.png',
    mobileImage: null,
    bannerType: null,
    url: null,
    isExternalUrl: null,
    isStatic: false
  },
  {
    _id: '4',
    name: null,
    title: null,
    subTitle: null,
    description: null,
    webBg: './assets/images/carousel/background/bg5.jpg',
    mobileBg: null,
    webImage: './assets/images/carousel/Image4.png',
    mobileImage: null,
    bannerType: null,
    url: null,
    isExternalUrl: null,
    isStatic: true
  },
];
