export const BANNER: any[] = [
  {
    _id: '1',
    name: 'Slicing Through Complexity, Like a Ninja',
    subTitle: 'To Advancing the Software Industry with Agility, Expertise, and Innovative Solutions',
    description: '',
    image: './assets/images/banner/2.jpg',
    mobileImage: './assets/images/3.jpg',
    sideImage: './assets/images/logo.jpg',
    bannerType: '',
    url: '',
    isExternalUrl: '',
  },
  {
    _id: '2',
    name: 'Elevating Technology, the Ninja Way',
    subTitle: 'To Advancing the Software Industry with Agility, Expertise, and Innovative Solutions',
    description: '',
    image: './assets/images/banner/1.jpg',
    mobileImage: './assets/images/1.jpg',
    sideImage: '',
    bannerType: '',
    url: '',
    isExternalUrl: '',
  },
  {
    _id: '3',
    name: 'Where Innovation Strikes Silently',
    subTitle: 'To Advancing the Software Industry with Agility, Expertise, and Innovative Solutions',
    description: '',
    image: './assets/images/banner/banner-1.png',
    mobileImage: './assets/images/banner-1.png',
    sideImage: './assets/images/logo.jpg',
    bannerType: '',
    url: '',
    isExternalUrl: '',
  },
];
